language: r
sudo: false
cache: packages
bioc_required: true
warnings_are_errors: false

addons:
  apt:
    packages:
      - r-recommended

script:
  - make install
  - make test

notifications:
  email: false

env:
  global:
    - R_CHECK_ARGS="--no-build-vignettes --no-manual"
    - _R_CHECK_TIMINGS_="0"

cache: 
  timeout: 1000

r_github_packages:
  - cran/survival
  - cran/Hmisc
