language: r
r: bioc-release
sudo: required
bioc_required: true
warnings_are_errors: false

cache:
  packages: true
  apt: true
  timeout: 1000

## deploy:
##   skip_cleanup: true

env:
  global:
    - R_CHECK_ARGS="--no-build-vignettes --no-manual"
    - _R_CHECK_TIMINGS_="0"

script:
  - make install
  - make test

r_binary_packages:
  - testthat acepack ade4 affy AnnotationDbi AnnotationForge AnnotationHub base64enc Biobase BiocGenerics BiocInstaller Biostrings biomaRt bumphunter Category caTools clusterProfiler corpcor corrplot DBI DESeq2 DESeq devtools directlabels dplyr doParallel DOSE EDASeq edgeR ffpe fission Formula gdata genbankr genefilter genomeIntervals GenomeInfoDb GenomicFeatures genoPlotR GenomicRanges ggdendro ggrepel GO.db googleVis goseq GOstats gplots graph gProfileR GSEABase gtools gridExtra hash Heatplus Hmisc htmlTable igraph inflection IRanges iterators jsonlite KEGGgraph KEGGREST knitr lattice limma matrixStats motifRG multtest mygene openxlsx OrganismDbi pander parallel pasilla pathview plyr preprocessCore qvalue RamiGO RColorBrewer ReactomePA readr rentrez reshape2 RCurl rGADEM Rgraphviz rmarkdown RMySQL robustbase reshape rjson robust Rsamtools rtracklayer RUVSeq S4Vectors scales seqinr seqLogo statmod stringi stringr survival sva taxize testthat topGO variancePartition xtable XVector survJamda

notifications:
  email: false
