language: r
r: bioc-release
##sudo: required
bioc_required: true
warnings_are_errors: false

cache:
  packages: true
  apt: true
  timeout: 1000
  directories:
    - $TRAVIS_BUILD_DIR/packrat/src
    - $TRAVIS_BUILD_DIR/packrat/lib

deploy:
  skip_cleanup: true

env:
  global:
    - USE_PACKRAT=1
    - R_CHECK_ARGS="--no-build-vignettes --no-manual"
    - _R_CHECK_TIMINGS_="0"

r_github_packages:
  - cran/survival
  - cran/Hmisc

##addons:
##  apt:
##    packages:
##      - r-recommended

##before_install:
##  - sudo apt-get -qq update
##  - sudo apt-get -y install $(apt-cache search r-bioc | awk '{print $1}' | grep -v "ebimage")

script:
  - make install
  - make test

install:
  - R -e "0" --args --bootstrap-packrat

notifications:
  email: false
