language: r
r: bioc-release
sudo: false
bioc_required: true
warnings_are_errors: false

cache:
  directories: ${TRAVIS_BUILD_DIR}/packrat/
  packages: true

env:
  global:
    - R_CHECK_ARGS="--no-build-vignettes --no-manual"
    - _R_CHECK_TIMINGS_="0"

install: 
  - R -e "0" --args --bootstrap-packrat

script:
  - make install
  - make test

notifications:
  email: false
