language: r
r: bioc-release
sudo: false
bioc_required: true
warnings_are_errors: false

cache:
  timeout: 3000
  packages: true
  directories:
          - ${TRAVIS_BUILD_DIR}/packrat/lib
          - ${TRAVIS_BUILD_DIR}/_bookdown_files

env:
  global:
    - R_CHECK_ARGS="--no-build-vignettes --no-manual"
    - _R_CHECK_TIMINGS_="0"
    - R_MAX_NUM_DLLS=256

install: 
  - make prereq
  - make install

script:
  - make test

notifications:
  email: false
