on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

name: CI
jobs:
  build:
    runs-on: ${{ matrix.config.os }}
    name: ${{ matrix.config.os }} (${{ matrix.config.r }})
    strategy:
      fail-fast: false
      matrix:
        R: [ '4.0.2' ]
    env:
       AUTHOR_TESTING: 1
       AUTOMATED_TESTING: 1
       RELEASE_TESTING: 1
       R_MAX_NUM_DLLS: 256
       R_LIBS_SITE: /home/runner/R
       R_LIBS: /home/runner/R
       R_LIBS_USER: /home/runner/R
       R_REMOTES_NO_ERRORS_FROM_WARNINGS: true

    steps:
      - uses: actions/checkout@master
      - name: Setup R and install packages
        uses: r-lib/actions/setup-R@v1
        with:
          r-version: ${{ matrix.R }}
      - run: |
          sudo apt-get update
          sudo apt-get install libcurl4-openssl-dev libcurl4 curl libnetcdf-dev default-jre default-jdk circos libxml2-dev

      - name: Install pandoc
      - uses: actions/checkout@master
      - uses: r-lib/actions/setup-pandoc@v1
      - run: echo "Installed pandoc."

      - name: Set Rprofile
        run: |
          echo "options(Ncpus = 2)" > ${HOME}/.Rprofile
          echo "r <- getOption('repos')" >> ${HOME}/.Rprofile
          echo 'r["CRAN"] <- "https://cloud.r-project.org"' >> ${HOME}/.Rprofile
          echo "options(repos=r)" >> ${HOME}/.Rprofile
          mkdir -p ${HOME}/R
          echo "R_LIBS_SITE=${HOME}/R" > ${HOME}/.bashrc
          export R_LIBS_SITE=${HOME}/R
          echo "R_LIBS=${HOME}/R" >> ${HOME}/.bashrc
          export R_LIBS=${HOME}/R
          echo "R_LIBS_USER=${HOME}/R" >> ${HOME}/.bashrc
          export R_LIBS_USER=${HOME}/R

      - name: Install R prerequisites
        run: make prereq

      - name: GoSemSim
        run: |
          devtools::install_github("YuLab-SMU/GOSemSim")
        shell: Rscript {0}

      - name: Query dependencies
        run: |
          install.packages("remotes")
          saveRDS(remotes::dev_package_deps(dependencies=TRUE), "depends.Rds", version=2)
        shell: Rscript {0}

      - name: Install system dependencies
        env:
          RHUB_PLATFORM: linux-x86_64-ubuntu-gcc
        run: |
          Rscript -e "remotes::install_github('r-hub/sysreqs')"
          sysreqs=$(Rscript -e "cat(sysreqs::sysreq_commands('DESCRIPTION'))")
          sudo -s eval "$sysreqs"

      - name: Install dependencies
        run: |
          remotes::install_deps(dependencies=TRUE)
          remotes::install_cran("lintr")
        shell: Rscript {0}

      - name: Install hpgltools prerequisites
        run: make deps

      - name: Run tests
        run: make test
