name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.config.os }}
    name: ${{ matrix.config.os }} (${{ matrix.config.r }})
    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: ubuntu-latest, r: '3.6'}
    env:
       AUTHOR_TESTING: 1
       AUTOMATED_TESTING: 1
       RELEASE_TESTING: 1
       R_MAX_NUM_DLLS: 256
       R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
       PERL_CARTON_PATH: $GITHUB_WORKSPACE/local

    steps:
    - uses: r-lib/actions/setup-r@master
      with:
        r-version: ${{ matrix.config.r }}
    - uses: r-lib/actions/setup-pandoc@master
    - uses: actions/checkout@v2
    - name: curl
      uses: wei/curl@master
      with:
        args: https://httpbin.org/get
    - name: Set Rprofile
      run: |
        echo "options(Ncpus = 2)" > ${HOME}/.Rprofile
        echo 'r <- getOption("repos")' >> ${HOME}/.Rprofile
        echo 'r["CRAN"] <- "https://cloud.r-project.org"' >> ${HOME}/.Rprofile
        echo 'options(repos = r)' >> ${HOME}/.Rprofile
    - name: Install dependencies
      run: |
        install.packages(c("remotes"))
        remotes::install_deps(dependencies = TRUE)
        remotes::install_cran("lintr")
      shell: Rscript {0}
    - name: Install R prerequisites
      run: make prereq
    - name: Install hpgltools prerequisites
      run: make deps
    - name: Run tests
      run: make test
    - name: Make vignettes
      run: make vt
