name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
       PERL_USE_UNSAFE_INC: 0
       AUTHOR_TESTING: 1
       AUTOMATED_TESTING: 1
       RELEASE_TESTING: 1
       R_MAX_NUM_DLLS: 256
       PERL_CARTON_PATH: $GITHUB_WORKSPACE/local
    strategy:
      matrix:
        perl-version:
          - 'latest'
    container:
      image: perl:${{ matrix.perl-version }}
    steps:
    - uses: actions/checkout@v1
    - name: Install R
      run: |
        apt-get update
        apt-get -yqq install r-cran-biocmanager r-base-dev r-base
        echo "options(Ncpus = 4)" > ${HOME}/.Rprofile
    - name: Install R prerequisites
      run: make prereq
    - name: How many cpus
      run: cat /proc/cpuinfo
    - name: Install hpgltools prerequisites
      run: make deps
