name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: debian-testing
    env:
       AUTHOR_TESTING: 1
       AUTOMATED_TESTING: 1
       RELEASE_TESTING: 1
       R_MAX_NUM_DLLS: 256
       R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
       PERL_CARTON_PATH: $GITHUB_WORKSPACE/local
    strategy:
      matrix:
        config:
          - {os: debian-testing, r: '3.6'}
    container:
      image: perl:${{ matrix.perl-version }}
    steps:
    - uses: r-lib/actions/setup-r@master
      with:
        r-version: ${{ matrix.config.r }}
    - uses: r-lib/actions/setup-pandoc@master
    - uses: actions/checkout@v1
    - name: Install R
      run: |
        apt-get update
        apt-get -yqq install r-cran-biocmanager r-base-dev r-base
        echo "options(Ncpus = 2)" > ${HOME}/.Rprofile
    - name: Install R prerequisites
      run: make prereq
    - name: Install hpgltools prerequisites
      run: make deps
    - name: Run tests
      run: make test
    - name: Make vignettes
      run: make vt
